server.port=8888
spring.application.name=config-server

# Configure Spring Cloud Config Server to read from a local folder (native profile)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:../config-repo,file:./config-repo,file:./ComputerStore/config-repo,file:${user.dir}/config-repo,file:${user.dir}/ComputerStore/config-repo,file:${user.dir}/../config-repo
