server.port=8084
spring.application.name=notification-service
spring.profiles.active=dev

# Import dynamic properties from Config Server
spring.config.import=optional:configserver:http://localhost:8888
