server.port=8761
spring.application.name=discovery-server

# Standalone Eureka Server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation for development to remove dead instances quickly
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=discovery-server
