server.port=8084

# Actuator Endpoints Exposure
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Prometheus Metrics Export
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=notification-service
management.metrics.tags.environment=dev

# Info endpoint
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
info.app.name=Notification Service
info.app.description=Computer Store - Notification Service
info.app.version=1.0.0
info.app.encoding=UTF-8

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
