spring.application.name=ComputerStore
server.port=8081

# Active profile: dev by default
spring.profiles.active=dev

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB