spring.application.name=ComputerStore
server.port=8081

# Conectarea la baza de date postgres (cea de baza)
# Am pastrat structura profesorului, dar folosim schema movies_schema
spring.datasource.url=jdbc:postgresql://localhost:5432/computer_store?currentSchema=computer_store
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.jdbc.datasource=DEBUG
spring.datasource.hikari.pool-name=ComputerHikariCP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect