spring.application.name=ComputerStore
server.port=8081

# Conectarea la baza de date postgres (cea de baz?)
# Am p?strat structura profesorului, dar folosim schema movies_schema
spring.datasource.url=jdbc:postgresql://localhost:5432/computer_shop_spring?currentSchema=computer_shop_spring
spring.datasource.username=postgres
spring.datasource.password=postgres

# Set?ri pentru a vedea ce se întâmpl? în consol? (ca la laborator)
logging.level.org.springframework.jdbc.datasource=DEBUG
spring.datasource.hikari.pool-name=ComputerHikariCP

# Hibernate - Foarte important pentru a crea schema ?i tabelele automat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect