spring.application.name=store-service
spring.profiles.active=dev

# Import configuration from Config Server
spring.config.import=optional:configserver:http://localhost:8888

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Activam Circuit Breaker pentru Feign Clients
feign.circuitbreaker.enabled=true

# Dezactivam TimeLimiter pentru Feign (folosim doar @CircuitBreaker, nu reactive)
spring.cloud.circuitbreaker.resilience4j.enable-semaphore-default-size-based-circuit-breaker-configuration=false
